---
title: "P8105 HW2"
output: html_document
---

```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
```

## Problem 1

```{r}
trash_wheel = 
  readxl::read_excel("./data/TWC.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N535") %>% 
  janitor::clean_names() %>% 
  filter(dumpster != "NA") %>% 
  mutate(sports_balls = round(sports_balls, digits = 0))
```

```{r}
prcp2018 = readxl::read_excel("./data/TWC.xlsx", sheet = "2018 Precipitation", skip = 1) %>%
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year = 2018)

prcp2019 = readxl::read_excel("./data/TWC.xlsx", sheet = "2019 Precipitation", skip = 1) %>%
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year = 2019)

prcp = full_join(prcp2018, prcp2019) %>% 
  mutate(month = month.name[month])
```

The Mr. Trash Wheel dataset contains `r nrow(trash_wheel)` observations in `r ncol(trash_wheel)` categories. 

The precipitation dataset contains `r nrow(prcp)` rows and `r ncol(prcp)` columns.  

## Problem 2

```{r}
pols_month = read_csv("./data/datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day")) %>% 
  mutate(month = as.numeric(month), year = as.numeric(year)) %>% 
  mutate(month = month.name[month]) %>% 
  mutate(president = ifelse(prez_gop == 0, "dem", "gop")) %>% 
  select(-c(prez_dem,prez_gop,day))
```

```{r}
snp = read_csv("./data/datasets/snp.csv") %>% 
  separate(date, into = c("month", "day", "year")) %>% 
  mutate(month = as.numeric(month), year = as.numeric(year)) %>%
  mutate(year = ifelse(year < 50, year + 2000, year + 1900)) %>% 
  arrange(year, month) %>% 
  mutate(month = month.name[month]) %>% 
  relocate(year, month)
```

```{r}
unemploy = read_csv("./data/datasets/unemployment.csv") %>%
  rename(year = Year) %>%
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "pct_unemployed"
    ) %>% 
  mutate(month = match(month, month.abb)) %>% 
  mutate(month = month.name[month])
```

```{r}
list1 = left_join(pols_month, snp)
list2 = left_join(list1, unemploy)
```


## Problem 3


